admin:
  username: **change_me**
  password: **change_me**

game:
  mode: classic
  round_time: 20
  start_time: 2019-11-30 15:30:00
  timezone: Europe/Rome

  default_score: 2500
  flag_lifetime: 5
  game_hardness: 10.0
  inflation: true

tasks:
  - checker: flags_shop/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 1
    name: Flags Shop
    places: 1
    puts: 1

teams:
  - ip: 172.25.1.0
    name: "Team 1"

  - ip: 172.25.2.0
    name: "Team 2"

  - ip: 172.25.3.0
    name: "Team 3"

  - ip: 172.25.4.0
    name: "Team 4"

  - ip: 172.25.5.0
    name: "Team 5"

  - ip: 172.25.6.0
    name: "Team 6"

  - ip: 172.25.7.0
    name: "Team 7"

  - ip: 172.25.8.0
    name: "Team 8"

  - ip: 172.25.9.0
    name: "Team 9"

  - ip: 172.25.10.0
    name: "Team 10"

  - ip: 172.25.11.0
    name: "Team 11"

  - ip: 172.25.12.0
    name: "Team 12"

  - ip: 172.25.13.0
    name: "Team 13"

  - ip: 172.25.14.0
    name: "Team 14"

  - ip: 172.25.15.0
    name: "Team 15"

  - ip: 172.25.16.0
    name: "Team 16"

  - ip: 172.25.17.0
    name: "Team 17"

  - ip: 172.25.18.0
    name: "Team 18"

  - ip: 172.25.19.0
    name: "Team 19"

  - ip: 172.25.20.0
    name: "Team 20"

  - ip: 172.25.21.0
    name: "Team 21"

  - ip: 172.25.22.0
    name: "Team 22"

  - ip: 172.25.23.0
    name: "Team 23"

  - ip: 172.25.24.0
    name: "Team 24"

  - ip: 172.25.25.0
    name: "Team 25"
