services:
  vulnbox1:
    container_name: vulnbox1
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.1.1
  vulnbox2:
    container_name: vulnbox2
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.2.1
  vulnbox3:
    container_name: vulnbox3
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.3.1
  vulnbox4:
    container_name: vulnbox4
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.4.1
  vulnbox5:
    container_name: vulnbox5
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.5.1
  vulnbox6:
    container_name: vulnbox6
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.6.1
  vulnbox7:
    container_name: vulnbox7
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.7.1
  vulnbox8:
    container_name: vulnbox8
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.8.1
  vulnbox9:
    container_name: vulnbox9
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.9.1
  vulnbox10:
    container_name: vulnbox10
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.10.1
  vulnbox11:
    container_name: vulnbox11
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.11.1
  vulnbox12:
    container_name: vulnbox12
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.12.1
  vulnbox13:
    container_name: vulnbox13
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.13.1
  vulnbox14:
    container_name: vulnbox14
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.14.1
  vulnbox15:
    container_name: vulnbox15
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.15.1
  vulnbox16:
    container_name: vulnbox16
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.16.1
  vulnbox17:
    container_name: vulnbox17
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.17.1
  vulnbox18:
    container_name: vulnbox18
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.18.1
  vulnbox19:
    container_name: vulnbox19
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.19.1
  vulnbox20:
    container_name: vulnbox20
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.20.1

networks:
  cyber_network:
    name: cyber_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.60.0.0/16

